# Generated by Django 5.0.4 on 2024-06-01 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
