# Generated by Django 5.0.4 on 2024-04-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('mac_address', models.CharField(max_length=100)),
                ('sleep_time', models.TimeField(default='22:00:00')),
                ('wake_time', models.TimeField(default='06:00:00')),
                ('preferred_temperature', models.FloatField(default=19.0)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('light_intensity', models.IntegerField()),
            ],
        ),
    ]
