# Generated by Django 5.0.4 on 2024-04-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_communication', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='device_id',
            new_name='device',
        ),
    ]
