# Generated by Django 5.0.4 on 2024-06-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device_communication", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="value",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="setting",
            name="value",
            field=models.FloatField(),
        ),
    ]
