# Generated by Django 5.0.4 on 2024-06-01 22:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_communication', '0004_alter_device_user_alter_measurement_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_type',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('device_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement_type',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Setting_type',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='device',
            old_name='device_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='preferred_temperature',
        ),
        migrations.RemoveField(
            model_name='device',
            name='sleep_time',
        ),
        migrations.RemoveField(
            model_name='device',
            name='wake_time',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='light_intensity',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='temperature',
        ),
        migrations.AddField(
            model_name='measurement',
            name='value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='device_communication.device_type'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='device_communication.measurement_type'),
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='device_communication.device')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='device_communication.setting_type')),
            ],
        ),
    ]
