# Generated by Django 5.0.4 on 2024-06-01 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "device_communication",
            "0005_device_type_measurement_type_setting_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="device",
            table="device",
        ),
    ]
