# Generated by Django 5.0.4 on 2024-06-01 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device_communication", "0006_alter_device_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="device_type",
            table="device_type",
        ),
        migrations.AlterModelTable(
            name="measurement",
            table="measurement",
        ),
        migrations.AlterModelTable(
            name="measurement_type",
            table="measurement_type",
        ),
        migrations.AlterModelTable(
            name="setting",
            table="setting",
        ),
        migrations.AlterModelTable(
            name="setting_type",
            table="setting_type",
        ),
    ]
